"""add user_uid to conversations

Revision ID: c73b09608952
Revises: b33f83cb3b5e
Create Date: 2026-02-16 13:17:14.555387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73b09608952'
down_revision: Union[str, Sequence[str], None] = 'b33f83cb3b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('user_uid', sa.String(length=128), nullable=False))
    op.create_index(op.f('ix_conversations_user_uid'), 'conversations', ['user_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_user_uid'), table_name='conversations')
    op.drop_column('conversations', 'user_uid')
    # ### end Alembic commands ###
